title: CJAdkins
author: Christopher J. Adkins
email: adkincj@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  A little bit of math, a little bit of code and a game here and there. Let's learn things together.

# social links
#twitter_username:
github_username: softyy
linkedin_username: adkinscj
codingame:
  id: 7d4b82a005185725a3c442367ca3848c5849451
  username: softyy
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

disqus:
  shortname: cjadkins

google_analytics: UA-100226425-1

show_excerpts: false # set to true to show excerpts on the homepage

paginate: 8
paginate_path: /page:num/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md
  - teaching.md
  - presentations.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
